apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileserver-db
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /dados
    server: 10.70.104.122

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileserver-db
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: fileserver-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:17.5
          imagePullPolicy: Always
          name: postgres
          envFrom:
            - secretRef:
                name: postgres-env
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: fileserver-db
              mountPath: /var/lib/postgresql/
      volumes:
        - name: fileserver-db
          persistentVolumeClaim:
            claimName: fileserver-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: proc-jur
  labels:
    app: proc-jur
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proc-jur
  template:
    metadata:
      labels:
        app: proc-jur
    spec:
      containers:
        - name: proc-jur
          image: jotabr092/proc-jur-service:1.0
          envFrom:
            - secretRef:
                name: default-env
            - secretRef:
                name: postgres-env
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: tls-volume
              mountPath: /etc/tls/keystore.p12
              subPath: keystore.p12
      volumes:
      - name: tls-volume
        secret:
          secretName: tls-secret
