apiVersion: v1
kind: Service
metadata:
  name: proc-jur
spec:
  selector:
    app: proc-jur
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-db-connection
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
  clusterIP: None